package com.yimeicloud.study.shiro_web.dao;

import java.util.List;

import com.yimeicloud.study.shiro_web.model.Permission;

public interface PermissionDao {

	/**
	 * 根据用户名取得权限信息
	 * @param name
	 * @return
	 */
	public List<String> selectByName(String name);
	
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	Permission selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int updateByPrimaryKey(Permission record);
}