package com.yimeicloud.study.shiro_web.dao;

import com.yimeicloud.study.shiro_web.model.User;

public interface UserDao {

	/**
	 * 插入用户
	 * @param user
	 * @return
	 */
	public int insert(User user);
	
	/**
	 * 通过用户名查找用户
	 * @param name
	 * @return
	 */
	public User selectByName(String name);
	
	
	
	
	
	
	
	
	
	
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	User selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed Jul 20 16:06:00 CST 2016
	 */
	int updateByPrimaryKey(User record);
}