package com.yimeicloud.study.shiro_web.dao;

import com.yimeicloud.study.shiro_web.model.UserRole;

public interface UserRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Jul 20 16:06:00 CST 2016
     */
    int deleteByPrimaryKey(UserRole key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Jul 20 16:06:00 CST 2016
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Jul 20 16:06:00 CST 2016
     */
    int insertSelective(UserRole record);
}